from sqlalchemy import Column, Integer, String, Float, BigInteger, Boolean, DateTime, Identity
# Importa Base desde el archivo database.py
from .database import Base

class ObrasMedicion(Base):
    __tablename__ = 'obras_medicion'

    id = Column(Integer, Identity(), primary_key=True, index=True)

    id_med_obr = Column(BigInteger, name='ID.MED.OBR', nullable=True)
    id_informante = Column(BigInteger, nullable=True)
    id_junta = Column(BigInteger, nullable=True)
    region = Column(Integer, nullable=True)
    provincia = Column(Integer, nullable=True)
    comuna = Column(Integer, nullable=True)
    utm_norte = Column(BigInteger, nullable=True)
    utm_este = Column(BigInteger, nullable=True)
    huso = Column(Integer, nullable=True)
    codigo = Column(String(255), nullable=True)
    naturaleza = Column(Integer, nullable=True) # nullable=True, cuidado con datos faltantes
    cod_cuenca = Column(Integer, nullable=True)
    nom_cuenca = Column(String(255), nullable=True)
    cod_acuifero = Column(Integer, nullable=True)
    nom_acuifero = Column(String(255), nullable=True)
    sector_sha = Column(String(255), nullable=True)
    cod_subcuenca = Column(Integer, nullable=True)
    nom_subcuenca = Column(String(255), nullable=True)
    cod_subsubcuenca = Column(Integer, nullable=True)
    nom_subsubcuenca = Column(String(255), nullable=True)
    cod_fuente_superficial = Column(Integer, nullable=True)
    nom_fuente_superficial = Column(String(255), nullable=True)
    nombre_fuente = Column(String(255), nullable=True)
    extrae_canal = Column(Boolean, nullable=True)
    nombre_canal = Column(String(255), nullable=True)
    apr = Column(Boolean, nullable=True)
    puntoalt = Column(Boolean, nullable=True)
    tiene_motobomba = Column(Boolean, nullable=True)
    tiene_bocatoma = Column(Boolean, nullable=True)
    tipo_bocatoma = Column(String(255), nullable=True)
    descarga_cauce_natural = Column(Boolean, nullable=True)
    habilitada = Column(Boolean, nullable=True)
    motivo_deshabilitada = Column(Integer, nullable=True)
    motivo_otra = Column(String(255), nullable=True)
    estado_obra = Column(Integer, nullable=True)
    motivo_cambio_estado = Column(String(255), nullable=True)
    fecha_cambio_estado = Column(DateTime, nullable=True) # Puede ser nulo
    motivo_cambio_informante = Column(String(255), nullable=True)
    nombre_obra = Column(String(255), nullable=True)
    tipo_obra = Column(Integer, nullable=True)
    cod_sector_sha = Column(Integer, nullable=True)
    representa_junta = Column(Boolean, nullable=True)
    parte_junta = Column(Boolean, nullable=True)
    rut_inf = Column(String(12), name='RUT.INF.', nullable=True) # nullable=True
    tip_inf = Column(Integer, name='TIP.INF.', nullable=True) # nullable=True
    nomb_inf = Column(String(255), name='NOMB.INF.', nullable=True)
    a_pat_inf = Column(String(255), name='A.PAT.INF.', nullable=True)
    a_mat_inf = Column(String(255), name='A.MAT.INF.', nullable=True)
    nacionalidad = Column(Integer, nullable=True)
    gen_inf = Column(Integer, name='GEN.INF', nullable=True)
    reg_inf = Column(Integer, name='REG.INF.', nullable=True)
    prov_inf = Column(Integer, name='PROV.INF.', nullable=True)
    com_inf = Column(Integer, name='COM.INF.', nullable=True)
    dir_inf = Column(String(255), name='DIR.INF', nullable=True)
    tel_fij_inf = Column(String(50), name='TEL.FIJ.INF.', nullable=True)
    tel_mov_inf = Column(String(50), name='TEL.MOV.INF', nullable=True)
    email_inf = Column(String(255), name='EMAIL.INF', nullable=True)
    rut_usu = Column(String(12), name='RUT.USU.', nullable=True) # nullable=True
    tip_usu = Column(Integer, name='TIP.USU.', nullable=True) # nullable=True
    nomb_usu = Column(String(255), name='NOMB.USU.', nullable=True)
    a_pat_usu = Column(String(255), name='A.PAT.USU.', nullable=True)
    a_mat_usu = Column(String(255), name='A.MAT.USU.', nullable=True)
    reg_usu = Column(Integer, name='REG.USU.', nullable=True)
    pro_usu = Column(Integer, name='PRO.USU.', nullable=True)
    com_usu = Column(Integer, nullable=True)
    gen_usu = Column(Integer, nullable=True)
    dir_usu = Column(String(255), nullable=True)
    tel_fij_usu = Column(String(50), nullable=True)
    tel_mov_usu = Column(String(50), nullable=True)
    email_usu = Column(String(255), nullable=True)
    id_med = Column(BigInteger, nullable=True)
    id_obra_captacion = Column(BigInteger, nullable=True)
    canal_transmision = Column(Integer, nullable=True)
    tipo_medicion = Column(Integer, nullable=True)
    fecha_medicion = Column(DateTime, nullable=True) # nullable=True
    fecha_origen = Column(DateTime, nullable=True)
    caudal = Column(Float, nullable=True)
    altura_limnimetrica = Column(Float, nullable=True)
    totalizador = Column(Float, nullable=True)
    nivel_freatico = Column(Float, nullable=True)
    rut_empresa = Column(String(12), nullable=True)

